//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDC.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanCu_DichVu
    {
        public string MaDC { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual DanCu DanCu { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
